# fly.toml app configuration file generated for damp-surf-5296 on 2025-11-22T14:49:25Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'damp-surf-5296'
primary_region = 'lax'

[build]
  dockerfile = './Dockerfile'

[env]
  BOOTSTRAP_PEER_NAME = 'peer1'
  BOOTSTRAP_PORT = '8080'
  BOOTSTRAP_TOKEN = 'password123'
  LOG_CONFS = 'true'
  PEERDNS = 'auto'
  PEERS = '1'
  PGID = '1000'
  PUID = '1000'
  SERVERPORT = '51820'

[[mounts]]
  source = 'config'
  destination = '/config'

[http_service]
  internal_port = 51820
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'udp'
  internal_port = 51820

  [[services.ports]]
    port = 51820

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 5
    soft_limit = 2

[[vm]]
  size = 'shared-cpu-1x'
